name: "gluster"

on:
  push:
    branches:
      - 'release-**'
      - 'main'
    paths:
      - '**/gluster.yml'
      - '**/gluster.sh'
  pull_request:
    branches:
      - 'release-**'
      - 'main'
    paths:
      - '**/gluster.yml'
      - '**/gluster.sh'
  schedule:
    - cron:  '30 20 * * *'
  workflow_dispatch:

jobs:
  gluster:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        run: |
          sudo .github/scripts/command/gluster.sh

      - name: Send Slack Notification
        if: ${{ failure() }}
        uses: juicedata/slack-notify-action@main
        with:
          channel-id: "${{ secrets.SLACK_CHANNEL_ID_FOR_PR_CHECK_NOTIFY }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"  

      - name: Setup upterm session
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'true' }}
        # if: failure()
        timeout-minutes: 60
        uses: lhotari/action-upterm@v1